name: Check JSON formatting using Prettier

on:
  push:
    paths:
    - "**.json"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout base repo
      uses: actions/checkout@v2

    - name: Install NPM dependencies
      run: npm ci

    - name: Run Prettier
      run: npm run format
